# Generated by Django 5.1.5 on 2025-01-20 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_employeeregistration_serviceregistry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='ecomapp.serviceregistry')),
            ],
        ),
    ]
