# Generated by Django 5.1.5 on 2025-01-20 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_bookinglist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglist',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='bookinglist',
            name='user',
        ),
        migrations.AddField(
            model_name='bookinglist',
            name='register',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinglist',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.servicerequest'),
        ),
    ]
