# Generated by Django 5.1.5 on 2025-01-21 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_servicerequest_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
