# Generated by Django 5.1.5 on 2025-01-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_alter_bookinglist_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglist',
            name='service_request',
        ),
        migrations.AlterField(
            model_name='bookinglist',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
