# Generated by Django 5.1.5 on 2025-01-21 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_remove_bookinglist_service_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinglist',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.servicerequest'),
        ),
    ]
