# Generated by Django 5.1.5 on 2025-01-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0014_alter_bookinglist_booking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
